name: Pull Request Stats

on: [push]


jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.PR_STATS_TOKEN }}
          period: 60
          exclude: sos-core-user