name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: fo2rist/pull-request-stats@master
        with:
          token: ${{ secrets.PR_STATS_ACCESS_TOKEN }}
          period: 60
          sort-by: 'REVIEWS'
          exclude-reviewers: sos-core-user